### ISSUE TITLE
Validations are appearing twice in docs

### ISSUE THREAD

**Issue by DominikPeters** [COMSOC-Community/prefsampling#3]
Validation results and charts both appear in a separate Validation section of the docs (https://comsoc-community.github.io/prefsampling/validation/index.html) but also as part of the reference section (e.g. https://comsoc-community.github.io/prefsampling/reference/ordinal/euclidean.html), and the two seem to not be the same. For example, for Euclidean, the reference version discusses the line case with fixed candidate positions, but the validation version does not.

Probably better to only have one version?

**Comment by Simon-Rey** [comment]
Indeed, I'm still in the middle of changing the docs but still decided to push the half-baked changes to see who was following :p 

I'll remove the graphs from the validation section. The graphs are now meant to only be with included in the reference of the functions.
